FROM osixia/phpldapadmin:0.9.0

# Copy into bootstrap so container init can sync into /var/www/phpldapadmin
COPY templates/posixAccount_ext.xml /var/www/phpldapadmin_bootstrap/templates/creation/posixAccount_ext.xml
#COPY templates/posixGroup_ext.xml /var/www/phpldapadmin_bootstrap/templates/creation/posixGroup_ext.xml
