UserParameter=AGENT.RDS_WriteThroughput[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_WriteLatency[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_WriteIOPS[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_SwapUsage[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_ReplicaLag[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_ReadThroughput[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_ReadLatency[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_ReadIOPS[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_NetworkTransmitThroughput[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_NetworkReceiveThroughput[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_FreeStorageSpace[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_FreeableMemory[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_DiskQueueDepth[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_DatabaseConnections[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
UserParameter=AGENT.RDS_CPUUtilization[*],/etc/zabbix/rds_status.py --metric $1 $2 $3 $4 $5 $6 $7 $8 $9
